-- Run with a database administrator through execute_sql. All fixtures roll back.
BEGIN;
DO $$
DECLARE u UUID; other_user UUID; a UUID; o UUID; test_org UUID; v INTEGER; denied BOOLEAN; snapshot JSONB; before_count BIGINT; broadcast_id UUID; automation_id UUID; pending_id UUID; flow_id UUID; run_id UUID;
BEGIN
 SELECT user_id INTO u FROM private.platform_admins ORDER BY created_at LIMIT 1;
 IF u IS NULL THEN RAISE EXCEPTION 'Provision a verified platform administrator before acceptance'; END IF;
 SELECT am.account_id,ac.organization_id INTO a,o FROM public.account_memberships am JOIN public.accounts ac ON ac.id=am.account_id
 WHERE am.user_id=u AND ac.branch_status='active' ORDER BY ac.created_at LIMIT 1;
 IF a IS NULL THEN RAISE EXCEPTION 'Acceptance needs an existing admin-owned branch'; END IF;
 ASSERT NOT has_table_privilege('authenticated','private.organization_product_access','UPDATE'), 'customer table update grant';
 ASSERT NOT has_function_privilege('anon','public.platform_admin_update_access(uuid,text,timestamptz,text,integer)','EXECUTE'), 'anonymous admin RPC grant';
 ASSERT (SELECT count(*) FROM public.organizations)=(SELECT count(*) FROM private.organization_product_access), 'missing access records';
 UPDATE private.product_access_settings SET enforcement_enabled=TRUE WHERE singleton;
 ASSERT NOT EXISTS(SELECT 1 FROM private.organization_product_access WHERE mode='complimentary' AND suspended_at IS NULL AND NOT private.organization_has_product_access(organization_id)), 'grandfathering';
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated','aal','aal1')::text,TRUE);
 PERFORM set_config('request.headers',jsonb_build_object('x-usefuldesk-account-id',a)::text,TRUE);
 ASSERT (public.platform_admin_status()->>'is_admin')::boolean, 'admin discovery';
 ASSERT (public.platform_admin_status()->>'mfa_required')::boolean, 'MFA requirement';
 denied:=FALSE;
 BEGIN PERFORM public.platform_admin_organizations(); EXCEPTION WHEN insufficient_privilege THEN denied:=TRUE; END;
 ASSERT denied,'aal1 can list customers';
 INSERT INTO public.organizations(name) VALUES('Trial acceptance — rolled back') RETURNING id INTO test_org;
 ASSERT (SELECT mode='trial' AND trial_started_at IS NULL FROM private.organization_product_access WHERE organization_id=test_org), 'unverified trial provision';
 INSERT INTO public.organization_memberships(organization_id,user_id,role) VALUES(test_org,u,'owner');
 ASSERT (SELECT trial_ends_at-trial_started_at=interval '14 days' FROM private.organization_product_access WHERE organization_id=test_org), 'verified trial duration';
 PERFORM private.start_verified_organization_trial(u);
 ASSERT (SELECT version=2 FROM private.organization_product_access WHERE organization_id=test_org), 'trial restarted';
 UPDATE private.organization_product_access SET mode='trial',trial_started_at=now()-interval '14 days',trial_ends_at=now(),suspended_at=NULL WHERE organization_id=o;
 ASSERT NOT private.account_has_product_access(a), 'exact expiry allowed';
 ASSERT public.has_account_membership(a),'identity membership lost';
 ASSERT NOT public.is_account_member(a),'operational membership allowed';
 ASSERT private.authorized_selected_account_id() IS NULL,'selected RLS allowed';
 ASSERT NOT private.can_receive_mobile_inbox_topic('account:'||a::text),'realtime allowed';
 ASSERT EXISTS(SELECT 1 FROM public.my_branch_accounts() WHERE account_id=a),'branch discovery lost';
 snapshot:=public.product_access_for_account(a);
 ASSERT snapshot->>'status'='expired' AND NOT (snapshot->>'allowed')::boolean,'support status unavailable';
 ASSERT public.product_access_request_support(a,'Acceptance support request')=public.product_access_request_support(a,'Repeat request'),'support dedupe';
 -- Genuine database role, not only a simulated JWT, proves RLS blocks old clients.
 SET LOCAL ROLE authenticated;
 ASSERT (SELECT count(*) FROM public.contacts WHERE account_id=a)=0,'expired contact SELECT';
 ASSERT (SELECT count(*) FROM public.accounts WHERE id=a)=1,'bootstrap account unreadable';
 ASSERT (SELECT count(*) FROM public.account_memberships WHERE account_id=a AND user_id=u)=1,'own membership unreadable';
 RESET ROLE;
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated','aal','aal2')::text,TRUE);
 SELECT version INTO v FROM private.organization_product_access WHERE organization_id=o;
 INSERT INTO public.broadcasts(user_id,account_id,name,template_name,status) VALUES(u,a,'Acceptance broadcast','acceptance','sending') RETURNING id INTO broadcast_id;
 INSERT INTO public.broadcast_recipients(broadcast_id,status,destination_phone) VALUES(broadcast_id,'pending','919999999999');
 INSERT INTO public.automations(user_id,account_id,name,trigger_type) VALUES(u,a,'Acceptance automation','new_contact_created') RETURNING id INTO automation_id;
 INSERT INTO public.automation_pending_executions(automation_id,user_id,account_id,next_step_position,run_at) VALUES(automation_id,u,a,0,now()) RETURNING id INTO pending_id;
 INSERT INTO public.flows(user_id,account_id,name,trigger_type) VALUES(u,a,'Acceptance flow','manual') RETURNING id INTO flow_id;
 INSERT INTO public.flow_runs(flow_id,user_id,account_id,status) VALUES(flow_id,u,a,'active') RETURNING id INTO run_id;
 SELECT count(*) INTO before_count FROM private.product_access_audit WHERE organization_id=o;
 snapshot:=public.platform_admin_update_access(o,'extend_trial',now()+interval '7 days','Acceptance extension',v);
 ASSERT (snapshot->>'allowed')::boolean,'extension did not restore';
 ASSERT (SELECT count(*) FROM private.product_access_audit WHERE organization_id=o)=before_count+2,'missing atomic access/queue audit';
 ASSERT (SELECT status='failed' FROM public.broadcasts WHERE id=broadcast_id),'broadcast will replay';
 ASSERT (SELECT status='failed' FROM public.automation_pending_executions WHERE id=pending_id),'automation will replay';
 ASSERT (SELECT status='failed' FROM public.flow_runs WHERE id=run_id),'flow will replay';
 denied:=FALSE;
 BEGIN PERFORM public.platform_admin_update_access(o,'suspend',NULL,'Stale request',v); EXCEPTION WHEN serialization_failure THEN denied:=TRUE; END;
 ASSERT denied,'stale version accepted';
 v:=(snapshot->'access'->>'version')::integer;
 snapshot:=public.platform_admin_update_access(o,'suspend',NULL,'Acceptance suspension',v);
 ASSERT NOT (snapshot->>'allowed')::boolean,'suspension allowed';
 UPDATE private.organization_product_access SET trial_ends_at=now() WHERE organization_id=o;
 v:=(snapshot->'access'->>'version')::integer;
 snapshot:=public.platform_admin_update_access(o,'restore',NULL,'Acceptance restore',v);
 ASSERT snapshot->>'status'='expired' AND NOT (snapshot->>'allowed')::boolean,'restore renewed expiry';
 v:=(snapshot->'access'->>'version')::integer;
 snapshot:=public.platform_admin_update_access(o,'activate',now()+interval '30 days','Acceptance manual term',v);
 ASSERT snapshot->>'status'='active' AND (snapshot->>'allowed')::boolean,'manual activation';
 SELECT id INTO other_user FROM auth.users WHERE id<>u LIMIT 1;
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',other_user,'role','authenticated','aal','aal2')::text,TRUE);
 denied:=FALSE;
 BEGIN PERFORM public.platform_admin_organizations(); EXCEPTION WHEN insufficient_privilege THEN denied:=TRUE; END;
 ASSERT denied,'customer aal2 can administer';
END $$;
ROLLBACK;
SELECT 'passed: database access and queued-work assertions; all test changes rolled back' acceptance;
